### PR TITLE
[Ready?]: Local/visits

### PR DESCRIPTION
**Pull request by simontegg**

### CODE REVIEW

**Comment by simontegg** [comment]
@iainkirkpatrick it'd be worth you having a look at this early. The base code is there but it works different on different platforms. And because we actually need to move the device to test it its hard to test during development.

**Comment by iainkirkpatrick** [comment]
can do tomorrow @simontegg :)

**Comment by iainkirkpatrick** [comment]
To clarify @simontegg - you have incoporated what you need from this branch into https://github.com/Ecosify/COVID-Community-Health-App/pull/50? in which case this PR could close / branch be deleted?

**Comment by simontegg** [comment]
sort of. Only to remove a blocker. We still need a proper way of doing background location listening. I'll close and put that into another ticket.

**Pull request closed without merging**
