### PR TITLE
[Ready] Feat/auth

### PR DESCRIPTION
**Pull request by simontegg**

### CODE REVIEW

**Comment by simontegg** [comment]
I resolved conflicts in github gui in generated files (my lead to issues)

**Comment by agentlewis** [comment]
@simontegg I have pulled the branch and am running it locally, but just get `no current user`

image

Am I missing something in how I have navigated to this branch to test it? 

Looking through the code I couldn't spot the reason why this is happening.

**Comment by simontegg** [comment]
I didn't allow for the fact that a call to `Auth.currentAuthenticatedUser` will throw an error and exit into the `catch` block immediately. 

Working on fix now

**Comment by agentlewis** [comment]
image

**Pull request merged**
